version: '3'
services:
  mesh_generator:
    container_name: mesh_generator
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      - SUBJECT=PY20N005
    volumes:
      - $SUBJECTS_DIR:/data/derivatives/freesurfer


