version: '3'
services:
  mesh_generator:
    container_name: mesh_generator
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      - SUBJECT=fsaverage
    volumes:
      - $SUBJECTS_DIR:/data

